In [103]:
import numpy as np
import numpy as np
from numpy.lib.stride_tricks import as_strided

# Neural Networks - Mạng neural nhân tạo

## Thiết kế mạng neural nhân tạo nhận diện hai mẫu

<img align="left" width="256" height="256" src="./figs/v_character.png">

<img align="left" width="256" height="256" src="./figs/o_character.png">

## Số hóa 2 mẫu trên
Ta nhận thấy, hai mẫu trên được biểu diễn trên một lưới 3x3, trên lưới có 2 loại ô: ô màu trắng và ô màu đen. <br>
Ta mô hình hóa hai mẫu trên bằng hai ma trận, kích thước 3x3, ô mang màu đen tương ứng giá trị 1 và ô màu trắng tương ứng giá trị 0. <br>

Mẫu 01:<br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>

Mẫu 02:<br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>


In [104]:
origin_model_v = np.array([1, 0, 1, 1, 0, 1, 0, 1, 0])

origin_model_o = np.array([1, 1, 1, 1, 0, 1, 1, 1, 1])

## Tiền xử lý
Bao xung quanh hai ma trận mô hình hóa hai mẫu bằng những con số 0. <br>

Mẫu 01:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 02:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

In [105]:
def pre_processing_input(origin_model):
    np_arr =  np.array(origin_model).reshape((3,3))
    result =  np.zeros(np_arr.shape + np.array(2), np_arr.dtype)
    result[1:-1,1:-1] = np_arr 
    return result

In [106]:
pre_processing_origin_model_v = pre_processing_input(origin_model_v)
pre_processing_origin_model_o = pre_processing_input(origin_model_o)

print(pre_processing_origin_model_v)
print(pre_processing_origin_model_o)

[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


## Phân tích thành các thành phần 3x3

Sau giai đoạn tiền xử lý, ta có mẫu 1 như sau: <br>
Mẫu 01:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Với một cửa số 3x3, ta bắt đầu trượt từ vị trí (0,0) với width step = 1 <br>
Mỗi lần trượt, ta thu được một ma trận kích thước 3x3
Với mẫu số 1, ta được <br>
Mẫu 01.0:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 01.1:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>

Mẫu 01.2:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 01.3:<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>

Mẫu 01.4:<br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>

Mẫu 01.5:<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 01.6:<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 01.7:<br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 01.8:<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Với mẫu số 2, ta được <br>
Mẫu 02:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 02.0:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 02.1:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>

Mẫu 02.2:<br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 02.3:<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>

Mẫu 02.4:<br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>

Mẫu 02.5:<br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 02.6:<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 02.7:<br>
1&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;1 <br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;1 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

Mẫu 02.8:<br>
0&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
1&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;0 <br>
0&nbsp;&nbsp;&nbsp;0&nbsp;&nbsp;&nbsp;0 <br>

In [107]:
def anlyze_preprocessing_matrix_model(arr, window_shape, steps):
    in_shape = np.array(arr.shape[-len(steps):])  
    window_shape = np.array(window_shape)  
    steps = np.array(steps)  
    nbytes = arr.strides[-1]  
    window_strides = tuple(np.cumprod(arr.shape[:0:-1])[::-1]) + (1,)
    step_strides = tuple(window_strides[-len(steps):] * steps)
    strides = tuple(int(i) * nbytes for i in step_strides + window_strides)
    outshape = tuple((in_shape - window_shape) // steps + 1)
    outshape = outshape + arr.shape[:-len(steps)] + tuple(window_shape)
    return as_strided(arr, shape=outshape, strides=strides, writeable=False)

In [108]:
V_Train = anlyze_preprocessing_matrix_model(pre_processing_origin_model_v, window_shape=(3, 3), steps=(1, 1))
O_Train = anlyze_preprocessing_matrix_model(pre_processing_origin_model_o, window_shape=(3, 3), steps=(1, 1))

print(V_Train)

print(O_Train)

[[[[0 0 0]
   [0 1 0]
   [0 1 0]]

  [[0 0 0]
   [1 0 1]
   [1 0 1]]

  [[0 0 0]
   [0 1 0]
   [0 1 0]]]


 [[[0 1 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 1]
   [1 0 1]
   [0 1 0]]

  [[0 1 0]
   [0 1 0]
   [1 0 0]]]


 [[[0 1 0]
   [0 0 1]
   [0 0 0]]

  [[1 0 1]
   [0 1 0]
   [0 0 0]]

  [[0 1 0]
   [1 0 0]
   [0 0 0]]]]
[[[[0 0 0]
   [0 1 1]
   [0 1 0]]

  [[0 0 0]
   [1 1 1]
   [1 0 1]]

  [[0 0 0]
   [1 1 0]
   [0 1 0]]]


 [[[0 1 1]
   [0 1 0]
   [0 1 1]]

  [[1 1 1]
   [1 0 1]
   [1 1 1]]

  [[1 1 0]
   [0 1 0]
   [1 1 0]]]


 [[[0 1 0]
   [0 1 1]
   [0 0 0]]

  [[1 0 1]
   [1 1 1]
   [0 0 0]]

  [[0 1 0]
   [1 1 0]
   [0 0 0]]]]


In [109]:
class NeuralNetwork:
    def __init__(self):
        # Ma trận trọng số cho lần threshold 1
        self.weight = np.array([-1, -1, -1, -1, 2, -1, -1, -1, -1])
        # Ma trận trọng số cho lần threshold cuối
        self.weight_final = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1])
        # Thông số threshold
        self.threshold = 0.5

    # Hàm tiền xử lý xử liệu
    def pre_processing_input(self, origin_model):
        np_arr =  np.array(origin_model).reshape((3,3))
        result =  np.zeros(np_arr.shape + np.array(2), np_arr.dtype)
        result[1:-1,1:-1] = np_arr 
        return result

    # Hàm trượt cửa sổ 3x3
    def anlyze_preprocessing_matrix_model(self, matrix, window_shape, steps):
        in_shape = np.array(matrix.shape[-len(steps):])  
        window_shape = np.array(window_shape)  
        steps = np.array(steps)  
        nbytes = matrix.strides[-1]  
        window_strides = tuple(np.cumprod(matrix.shape[:0:-1])[::-1]) + (1,)
        step_strides = tuple(window_strides[-len(steps):] * steps)
        strides = tuple(int(i) * nbytes for i in step_strides + window_strides)
        outshape = tuple((in_shape - window_shape) // steps + 1)
        outshape = outshape + matrix.shape[:-len(steps)] + tuple(window_shape)
        return as_strided(matrix, shape=outshape, strides=strides, writeable=False).reshape(9,9)

    # Hàm dot product
    def dot_product(self, w, x):
        return np.sign(np.dot(w.T, x))

    # Hàm phân ngưỡng
    def func_threshold(self, sum_dot_product):
        return (0, 1)[sum_dot_product > self.threshold]

    # Hàm thực thi và cho ra kết quả nhận dạng: 1 -> Chữ V, 0 -> Chữ O
    def fit(self, X):
        layer_y = []
        for x in X:
            y = self.dot_product(self.weight, x)
            layer_y.append(self.func_threshold(y))
        return self.func_threshold(self.dot_product(self.weight_final, layer_y))

In [111]:
net = NeuralNetwork()
pre_processing_v = net.pre_processing_input(origin_model_v)
pre_processing_o = net.pre_processing_input(origin_model_o)

anlyze_preprocessing_v = net.anlyze_preprocessing_matrix_model(pre_processing_v, window_shape=(3, 3), steps=(1, 1))
anlyze_preprocessing_o = net.anlyze_preprocessing_matrix_model(pre_processing_o, window_shape=(3, 3), steps=(1, 1))

result_v = net.fit(anlyze_preprocessing_v)
result_o = net.fit(anlyze_preprocessing_o)

print(result_v)
print(result_o)

1
0
